### Create Mascota
POST http://localhost:5000/mascotas
Content-Type: application/json

{
    "nombre": "Dante",
    "edad": 1,
    "tipo": "Perro",
    "raza": "Pitbull",
    "sexo": "Macho"
}

### Get Mascotas
GET http://localhost:5000/mascotas


### Create Mascota
PUT http://localhost:5000/mascotas/67c7c113c0c378ca32d04e60
Content-Type: application/json

{
    "nombre": "Dantesito",
    "edad": 5,
    "tipo": "Perro",
    "raza": "Pitbull",
    "sexo": "Macho"
}

### Delete Mascota
DELETE http://localhost:5000/mascotas/67c7c113c0c378ca32d04e60